version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    restart: always
    depends_on:
      elastic:
        condition: "service_started"
      postgres:
        condition: "service_started"
    ports:
      - "27361:80"
    networks:
      - elastic
    links:
      - elastic
      - postgres

  elastic:
    image: elastic/elasticsearch:8.9.1
    container_name: elastic
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    volumes:
      - es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 4000M

  postgres:
    container_name: postgres
    image: postgres:16.0
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
       - ${PWD}/create_tables/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - elastic
    ports:
      - "5432:5432"

networks:
  elastic:
    driver: bridge

volumes:
  es-data:
    driver: local
  postgres:
    driver: local